import type { Metadata } from "next";
import { Inter, Exo } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
const inter = Inter({ subsets: ["latin"] });
const exo = Exo({ subsets: ["latin"], weight: "700" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className} style={{ background: "#f0e8ca" }}>
        <main className="home">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
